### ISSUE TITLE
Throws this error: "The URI segment '$ref' is invalid after the segment"

### ISSUE THREAD

**Issue by alozadaDonostek** [ashlega/ITAintBoring.PCFControls#43]
I installed the solution ItAintBoringPCFControls.zip, then placed in a form and configured as indicated. The control does display all the records in the related entity but after making a selection, it displays the error mentioned on the title "The URI segment '$ref' is invalid after the segment ..."

Has anybody run into this?

**Comment by IamPaddyByrne** [comment]
I'm experiencing the same problem. I haven't worked out what it is yet so if you get there first please let me know how to resolve it.

**Comment by alozadaDonostek** [comment]
Actually, I was able to resolve it. The issue was with the relationship name. I was using all lower-case for that name which apparently doesn't work. You need to place the relationship name exactly as it appears in the solution editor, so if you have mixed casing (lower and upper)  you know what to do.

**Comment by IamPaddyByrne** [comment]
Cheers Alozada! That's sorted it out.
